In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"../data/sample/combined_dataset.csv")
df

,Employee_ID,Name,Age,Department,Salary,Experience,Joining_Date,City
0,EMP001,Rahul Sharma,28,IT,85000.0,5,12-04-2023,Mumbai
1,EMP001,Rahul Sharma,28,IT,85000.0,5,12-04-2023,Mumbai
2,EMP002,Jane Doe,32,it,95000.0,8,05/18/2022,Bangalore
3,EMP003,Amit Patel,-5,IT,110000.0,12,20-11-2021,Bengaluru
4,EMP004,Priya Rai,20,Marketing,55000.0,25,01-09-2025,BLR
5,EMP005,Vikram Singh,45,HR,NaN,15,Jan-24,Delhi
6,EMP006,A1ex F1etcher,38,Information Technology,1250000.0,14,15-07-2020,New Delhi
7,EMP007,Sneha Reddy,29,Sales,1000000.0,6,31-02-2025,Hyderabad
8,EMP002,Michael Scott,43,Management,60000.0,20,01-04-2024,Scranton
9,EMP008,Rohan Das,32 Years,I.T.,-45000.0,7,10-10-2027,Bangalore
10,EMP009,NaN,31,Finance,72000.0,4,14-01-2025,Pune
11,EMP010,Kabir Kapoor,35,NaN,98000.0,9,22-08-2023,Chennai

In [3]:
df.head()

,Employee_ID,Name,Age,Department,Salary,Experience,Joining_Date,City
0,EMP001,Rahul Sharma,28,IT,85000.0,5,12-04-2023,Mumbai
1,EMP001,Rahul Sharma,28,IT,85000.0,5,12-04-2023,Mumbai
2,EMP002,Jane Doe,32,it,95000.0,8,05/18/2022,Bangalore
3,EMP003,Amit Patel,-5,IT,110000.0,12,20-11-2021,Bengaluru
4,EMP004,Priya Rai,20,Marketing,55000.0,25,01-09-2025,BLR

In [4]:
df.shape

(12, 8)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   12 non-null     str
 1   Name          11 non-null     str
 2   Age           12 non-null     str
 3   Department    11 non-null     str
 4   Salary        11 non-null     float64
 5   Experience    12 non-null     int64
 6   Joining_Date  12 non-null     str
 7   City          12 non-null     str
dtypes: float64(1), int64(1), str(6)
memory usage: 900.0 bytes

In [6]:
df.describe()

             Salary  Experience
count  1.100000e+01   12.000000
mean   2.604545e+05   10.833333
std    4.330486e+05    6.589707
min   -4.500000e+04    4.000000
25%    6.600000e+04    5.750000
50%    8.500000e+04    8.500000
75%    1.040000e+05   14.250000
max    1.250000e+06   25.000000

In [13]:
df.describe(include='all')

,Employee_ID,Name,Age,Department,Salary,Experience,Joining_Date,City
count,12,11,12,11,1.100000e+01,12.000000,12,12
unique,10,10,11,9,NaN,NaN,11,10
top,EMP001,Rahul Sharma,28,IT,NaN,NaN,12-04-2023,Mumbai
freq,2,2,2,3,NaN,NaN,2,2
mean,NaN,NaN,NaN,NaN,2.604545e+05,10.833333,NaN,NaN
std,NaN,NaN,NaN,NaN,4.330486e+05,6.589707,NaN,NaN
min,NaN,NaN,NaN,NaN,-4.500000e+04,4.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,6.600000e+04,5.750000,NaN,NaN
50%,NaN,NaN,NaN,NaN,8.500000e+04,8.500000,NaN,NaN
75%,NaN,NaN,NaN,NaN,1.040000e+05,14.250000,NaN,NaN
max,NaN,NaN,NaN,NaN,1.250000e+06,25.000000,NaN,NaN

# Null Values Operation

In [14]:
df.isnull()

,Employee_ID,Name,Age,Department,Salary,Experience,Joining_Date,City
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,True,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,True,False,False,False,False,False,False
11,False,False,False,True,False,False,False,False

In [15]:
df.isnull().sum()

Employee_ID     0
Name            1
Age             0
Department      1
Salary          1
Experience      0
Joining_Date    0
City            0
dtype: int64

In [16]:
missing_percentage = (df.isnull().sum() / df.shape[0]) * 100      #we can also write len(df)in place of df.shape[0]
missing_percentage

Employee_ID     0.000000
Name            8.333333
Age             0.000000
Department      8.333333
Salary          8.333333
Experience      0.000000
Joining_Date    0.000000
City            0.000000
dtype: float64

In [17]:
# Calculate missing percentage
missing_percentage = (df.isnull().sum() / len(df)) * 100

# Empty list to store report
report = []

# Generate report
for column in missing_percentage.index:            # .index will provide cloumns name

    percentage = missing_percentage[column]

    if percentage == 0:
        severity = "No Issue"

    elif percentage <= 5:
        severity = "Low"

    elif percentage <= 20:
        severity = "Medium"

    else:
        severity = "High"

    record = {
        "Column": column,
        "Missing Percentage": round(percentage, 2),
        "Severity": severity
    }

    report.append(record)

print(report)

[{'Column': 'Employee_ID', 'Missing Percentage': np.float64(0.0), 'Severity': 'No Issue'}, {'Column': 'Name', 'Missing Percentage': np.float64(8.33), 'Severity': 'Medium'}, {'Column': 'Age', 'Missing Percentage': np.float64(0.0), 'Severity': 'No Issue'}, {'Column': 'Department', 'Missing Percentage': np.float64(8.33), 'Severity': 'Medium'}, {'Column': 'Salary', 'Missing Percentage': np.float64(8.33), 'Severity': 'Medium'}, {'Column': 'Experience', 'Missing Percentage': np.float64(0.0), 'Severity': 'No Issue'}, {'Column': 'Joining_Date', 'Missing Percentage': np.float64(0.0), 'Severity': 'No Issue'}, {'Column': 'City', 'Missing Percentage': np.float64(0.0), 'Severity': 'No Issue'}]

In [18]:
report_df = pd.DataFrame(report)
report_df

         Column  Missing Percentage  Severity
0   Employee_ID                0.00  No Issue
1          Name                8.33    Medium
2           Age                0.00  No Issue
3    Department                8.33    Medium
4        Salary                8.33    Medium
5    Experience                0.00  No Issue
6  Joining_Date                0.00  No Issue
7          City                0.00  No Issue

# Duplicate Values Operation

In [19]:
duplicate_rows = df.duplicated()
duplicate_rows

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [20]:
duplicate_count = duplicate_rows.sum()
print("Total duplicate rows: ",duplicate_count)

Total duplicate rows:  1

In [21]:
duplicate_records = df[duplicate_rows]
duplicate_records

,Employee_ID,Name,Age,Department,Salary,Experience,Joining_Date,City
1,EMP001,Rahul Sharma,28,IT,85000.0,5,12-04-2023,Mumbai

In [22]:
clean_df = df.drop_duplicates()
clean_df

,Employee_ID,Name,Age,Department,Salary,Experience,Joining_Date,City
0,EMP001,Rahul Sharma,28,IT,85000.0,5,12-04-2023,Mumbai
2,EMP002,Jane Doe,32,it,95000.0,8,05/18/2022,Bangalore
3,EMP003,Amit Patel,-5,IT,110000.0,12,20-11-2021,Bengaluru
4,EMP004,Priya Rai,20,Marketing,55000.0,25,01-09-2025,BLR
5,EMP005,Vikram Singh,45,HR,NaN,15,Jan-24,Delhi
6,EMP006,A1ex F1etcher,38,Information Technology,1250000.0,14,15-07-2020,New Delhi
7,EMP007,Sneha Reddy,29,Sales,1000000.0,6,31-02-2025,Hyderabad
8,EMP002,Michael Scott,43,Management,60000.0,20,01-04-2024,Scranton
9,EMP008,Rohan Das,32 Years,I.T.,-45000.0,7,10-10-2027,Bangalore
10,EMP009,NaN,31,Finance,72000.0,4,14-01-2025,Pune
11,EMP010,Kabir Kapoor,35,NaN,98000.0,9,22-08-2023,Chennai

# Data Type Validation

In [23]:
df.dtypes

Employee_ID         str
Name                str
Age                 str
Department          str
Salary          float64
Experience        int64
Joining_Date        str
City                str
dtype: object

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   12 non-null     str
 1   Name          11 non-null     str
 2   Age           12 non-null     str
 3   Department    11 non-null     str
 4   Salary        11 non-null     float64
 5   Experience    12 non-null     int64
 6   Joining_Date  12 non-null     str
 7   City          12 non-null     str
dtypes: float64(1), int64(1), str(6)
memory usage: 900.0 bytes

In [25]:
df["Age"] = pd.to_numeric(df["Age"],errors="coerce")
df.dtypes

Employee_ID         str
Name                str
Age             float64
Department          str
Salary          float64
Experience        int64
Joining_Date        str
City                str
dtype: object

In [26]:
# by errors="coerce" which row are not in datatime64 formate then it will convert in NAT
# (missing data), by this program will not throw error 
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"],errors="coerce")  

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   12 non-null     str
 1   Name          11 non-null     str
 2   Age           11 non-null     float64
 3   Department    11 non-null     str
 4   Salary        11 non-null     float64
 5   Experience    12 non-null     int64
 6   Joining_Date  5 non-null      datetime64[us]
 7   City          12 non-null     str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 900.0 bytes

In [27]:
df

,Employee_ID,Name,Age,Department,Salary,Experience,Joining_Date,City
0,EMP001,Rahul Sharma,28.0,IT,85000.0,5,2023-12-04,Mumbai
1,EMP001,Rahul Sharma,28.0,IT,85000.0,5,2023-12-04,Mumbai
2,EMP002,Jane Doe,32.0,it,95000.0,8,NaT,Bangalore
3,EMP003,Amit Patel,-5.0,IT,110000.0,12,NaT,Bengaluru
4,EMP004,Priya Rai,20.0,Marketing,55000.0,25,2025-01-09,BLR
5,EMP005,Vikram Singh,45.0,HR,NaN,15,NaT,Delhi
6,EMP006,A1ex F1etcher,38.0,Information Technology,1250000.0,14,NaT,New Delhi
7,EMP007,Sneha Reddy,29.0,Sales,1000000.0,6,NaT,Hyderabad
8,EMP002,Michael Scott,43.0,Management,60000.0,20,2024-01-04,Scranton
9,EMP008,Rohan Das,NaN,I.T.,-45000.0,7,2027-10-10,Bangalore
10,EMP009,NaN,31.0,Finance,72000.0,4,NaT,Pune
11,EMP010,Kabir Kapoor,35.0,NaN,98000.0,9,NaT,Chennai

# Outliers

In [28]:
q1 = df['Salary'].quantile(0.25)
q2 = df['Salary'].quantile(0.50)
q3 = df['Salary'].quantile(0.75)

print(q1,q2,q3)

66000.0 85000.0 104000.0

In [29]:
IQR = q3 - q1
print(IQR)

38000.0

In [30]:
lower_bound = q1 - (1.5 * IQR)
upper_bound = q3 + (1.5 * IQR)

outliers = df[
    (df['Salary'] < lower_bound) |
    (df['Salary'] > upper_bound)
]

outliers

,Employee_ID,Name,Age,Department,Salary,Experience,Joining_Date,City
6,EMP006,A1ex F1etcher,38.0,Information Technology,1250000.0,14,NaT,New Delhi
7,EMP007,Sneha Reddy,29.0,Sales,1000000.0,6,NaT,Hyderabad
9,EMP008,Rohan Das,NaN,I.T.,-45000.0,7,2027-10-10,Bangalore

# Dataset Overview Report

In [31]:
overview = {

    "Rows": df.shape[0],

    "Columns": df.shape[1],

    "Numeric Columns":
    len(df.select_dtypes(include=["number"]).columns),

    "Categorical Columns":
    len(df.select_dtypes(include=["object", "category"]).columns),

    "Datetime Columns":
    len(df.select_dtypes(include=["datetime"]).columns),

    "Memory Usage (MB)":
    round(
        df.memory_usage(deep=True).sum() / (1024 * 1024),
        2
    ),

    "Missing Values":
    df.isnull().sum().sum(),

    "Duplicate Rows":
    df.duplicated().sum()
}

overview_report_df = pd.DataFrame(
    overview.items(),
    columns=["Metric", "Value"]
)

overview_report_df

C:\Users\arman\AppData\Local\Temp\ipykernel_18424\3742763324.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  len(df.select_dtypes(include=["object", "category"]).columns),

                Metric  Value
0                 Rows   12.0
1              Columns    8.0
2      Numeric Columns    3.0
3  Categorical Columns    4.0
4     Datetime Columns    1.0
5    Memory Usage (MB)    0.0
6       Missing Values   11.0
7       Duplicate Rows    1.0

# Missing Value Report

In [3]:
report = []

for column in df.columns:

    missing_count = df[column].isnull().sum()

    missing_percentage = (
        missing_count / len(df)
    ) * 100

    if missing_percentage == 0:
        severity = "None"
        recommendation = "No action needed"

    elif missing_percentage <= 5:
        severity = "Low"
        recommendation = "Fill missing values"

    elif missing_percentage <= 30:
        severity = "Medium"
        recommendation = "Investigate and impute"

    else:
        severity = "High"
        recommendation = "Review column usefulness"

    report.append({

        "Column": column,

        "Missing Count": missing_count,

        "Missing %": round(
            missing_percentage,
            2
        ),

        "Severity": severity,

        "Recommendation": recommendation

    })

missing_report_df = pd.DataFrame(report)

missing_report_df

NameError: name 'df' is not defined

# Duplicate Detection Report

In [33]:
total_rows = len(df)

duplicate_count = df.duplicated().sum()

duplicate_percentage = (
    duplicate_count / total_rows
) * 100

if duplicate_count == 0:
    status = "Clean"
    recommendation = "No action needed"

else:
    status = "Review Required"
    recommendation = (
        "Review duplicate records before removing"
    )

report = {

    "Total Rows": total_rows,

    "Duplicate Rows": duplicate_count,

    "Duplicate %": round(
        duplicate_percentage,
        2
    ),

    "Status": status,

    "Recommendation": recommendation

}

duplicate_report_df = pd.DataFrame(
    report.items(),
    columns=["Metric", "Value"]
)

duplicate_report_df

           Metric                                     Value
0      Total Rows                                        12
1  Duplicate Rows                                         1
2     Duplicate %                                      8.33
3          Status                           Review Required
4  Recommendation  Review duplicate records before removing

# Data type Report

In [34]:
report = []

for column in df.columns:
    current_type = str(df[column].dtype)

    if current_type == "object":
        recommended = "category"
        status = "Recommendation"
    else:
        recommended = current_type
        status = "Correct"

    record = {
        "Column" : column,
        "Current Type" : current_type,
        "Recommended Type" : recommended,
        "Status" : status
    }

    report.append(record)

datatype_report_df = pd.DataFrame(report)
datatype_report_df

         Column    Current Type Recommended Type   Status
0   Employee_ID             str              str  Correct
1          Name             str              str  Correct
2           Age         float64          float64  Correct
3    Department             str              str  Correct
4        Salary         float64          float64  Correct
5    Experience           int64            int64  Correct
6  Joining_Date  datetime64[us]   datetime64[us]  Correct
7          City             str              str  Correct

# Outliers Report

In [35]:
outlier_report = []

for column in df.select_dtypes(include=["number"]).columns:

    q1 = df[column].quantile(0.25)
    q3 = df[column].quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)

    outliers = (
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    )

    outlier_count = outliers.sum()

    status = (
        "Clean"
        if outlier_count == 0
        else "Review Required"
    )

    outlier_report.append({
                "Column": column,
                "Q1": q1,
                "Q3": q3,
                "IQR": iqr,
                "Lower Bound": lower_bound,
                "Upper Bound": upper_bound,
                "Outlier Count": outlier_count,
                "Status": status
            })

outlier_report_df = pd.DataFrame(outlier_report)

outlier_report_df

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Status
0,Age,28.00,36.50,8.5,15.25,49.25,1,Review Required
1,Salary,66000.00,104000.00,38000.0,9000.00,161000.00,3,Review Required
2,Experience,5.75,14.25,8.5,-7.00,27.00,0,Clean

# Dashboard

In [36]:
dashboard = {
    "Total Rows": df.shape[0],

    "Total Columns": df.shape[1],

    "Columns with Missing Values":
    (missing_report_df["Missing Count"] > 0).sum(),

    "Duplicate Rows":
    df.duplicated().sum(),

    "Data Type Issues":
    (datatype_report_df["Status"] == "Recommendation").sum(),

    "Outlier Columns":
    (outlier_report_df["Outlier Count"] > 0).sum()
}

dashboard_report_df = pd.DataFrame(
    dashboard.items(),
    columns=["Metric","Value"]
)

dashboard_report_df

                        Metric  Value
0                   Total Rows     12
1                Total Columns      8
2  Columns with Missing Values      5
3               Duplicate Rows      1
4             Data Type Issues      0
5              Outlier Columns      2